### ISSUE TITLE
Use Division

### ISSUE THREAD

**Issue by dodyg** [MichaelKMalak/flutter_practice#1]
https://pub.dev/packages/division

This package allows you to separate the style widgets

**Comment by MichaelKMalak** [comment]
Okay 👍

**Comment by dodyg** [comment]
Try building complex screen. You will see the limitation and the challenges of managing complex screens in Flutter. 

The way to fix it is to decompose the screens using more custom widgets.

**Comment by MichaelKMalak** [comment]
I see. 
I did something similar to that [here](https://github.com/MichaelKMalak/flutter_practice/blob/BMI/lib/gender_card.dart).

**Comment by MichaelKMalak** [comment]
I used division package [here](https://github.com/MichaelKMalak/flutter_practice/tree/BMI-with-packages).
