### ISSUE TITLE
Alternative

### ISSUE THREAD

**Issue by dodyg** [MichaelKMalak/flutter_practice#10]
Another interesting client side stack is this https://dotnet.microsoft.com/apps/aspnet/web-apps/blazor

This goes on the other direction of Flutter. Flutter starts from mobile to web, Blazor starts from web to mobile.

If you want to do a paid internship or a full time job, we have a real interesting development using Blazor currently going on.

**Comment by MichaelKMalak** [comment]
Sounds interesting. I'll check it out and return to you.

**Comment by MichaelKMalak** [comment]
https://github.com/MichaelKMalak/blazor_practice
